In [16]:
import pandas as pd
import numpy as np

In [17]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [18]:
df = pd.DataFrame(data, columns=columns)

In [19]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [20]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [21]:
df.loc[0]

Make                 Nissan
Model                Stanza
Year                   1991
Engine HP             138.0
Engine Cylinders          4
Transmission Type    MANUAL
Vehicle_Style         sedan
MSRP                   2000
Name: 0, dtype: object

In [22]:
df.iloc[0]

Make                 Nissan
Model                Stanza
Year                   1991
Engine HP             138.0
Engine Cylinders          4
Transmission Type    MANUAL
Vehicle_Style         sedan
MSRP                   2000
Name: 0, dtype: object

Element-wise operation
Like in NumPy, when we have an array we can apply an operation to all elements - if we multiply an array by 2, all elements get multiplied by 2. We can do the same with Pandas:

In [23]:
df['Engine HP']

0    138.0
1      NaN
2    218.0
3    194.0
4    261.0
Name: Engine HP, dtype: float64

In [24]:
df['Engine HP'] * 2

0    276.0
1      NaN
2    436.0
3    388.0
4    522.0
Name: Engine HP, dtype: float64

Filtering:
There are two parts here. The part inside the brackets is the condition - it returns a new boolean Series with False and True values. And the brackets themselves look at the values that are True and return only those rows:

In [25]:
# To look at all the cars that were manufactured after 2015

df[
    df['Year'] > 2015
]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [26]:
# To find all Nissan cars

df[
    df['Make'] == 'Nissan'
]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [27]:
# Combine conditions: cars that are manufactured by Nissan and produced after 2015

df[
    (df['Make'] == 'Nissan') & (df['Year'] > 2015)
]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

String operations

In [28]:
# Applying string methods directly to a string

'machine learning zoomcamp'.upper()

'MACHINE LEARNING ZOOMCAMP'

In [29]:
'machine learning zoomcamp'.split()

['machine', 'learning', 'zoomcamp']

In [30]:
'machine learning zoomcamp'.lower().replace(' ', '_')

'machine_learning_zoomcamp'

In [33]:
# Applying it to the Series the same way, via str

df['vehicle_style'] = df['Vehicle_Style'].str.lower().str.replace(' ', '_')
df['vehicle_style']

0          sedan
1          sedan
2    convertible
3        4dr_suv
4         pickup
Name: vehicle_style, dtype: str

In addition, there is a useful function called describe, which reports all the useful statistics at once: how many records there are (the size of the Series), the mean value, the standard deviation, the minimal value, the percentiles - 25th, 50th, 75th - and the max:

In [34]:
df['MSRP'].mean()

np.float64(30186.0)

In [35]:
df.MSRP.mean()

np.float64(30186.0)

In [36]:
df['MSRP'].describe()

count        5.000000
mean     30186.000000
std      18985.044904
min       2000.000000
25%      27150.000000
50%      32340.000000
75%      34450.000000
max      54990.000000
Name: MSRP, dtype: float64

In [37]:
df['Vehicle_Style'].unique()

<StringArray>
['sedan', 'Sedan', 'convertible', '4dr SUV', 'Pickup']
Length: 5, dtype: str

In [38]:
df['Vehicle_Style'].nunique()

5

In [39]:
df.nunique()

Make                 4
Model                5
Year                 3
Engine HP            4
Engine Cylinders     2
Transmission Type    2
Vehicle_Style        5
MSRP                 5
vehicle_style        4
dtype: int64

In [40]:
# Missing values

df.isnull()

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,vehicle_style
0,False,False,False,False,False,False,False,False,False
1,False,False,False,True,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False

In [41]:
df.isnull().sum()

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        0
MSRP                 0
vehicle_style        0
dtype: int64

In [42]:
df['Transmission Type']

0       MANUAL
1    AUTOMATIC
2       MANUAL
3    AUTOMATIC
4       MANUAL
Name: Transmission Type, dtype: str

In [44]:
df['Transmission Type'].unique()

<StringArray>
['MANUAL', 'AUTOMATIC']
Length: 2, dtype: str

In [43]:
df['Transmission Type'].value_counts()

Transmission Type
MANUAL       3
AUTOMATIC    2
Name: count, dtype: int64

In [45]:
df.groupby('Transmission Type')

In [49]:
df.groupby('Transmission Type').MSRP.mean().round(2)

Transmission Type
AUTOMATIC    30800.00
MANUAL       29776.67
Name: MSRP, dtype: float64

In [52]:
df.groupby('Transmission Type').MSRP.max()

Transmission Type
AUTOMATIC    34450
MANUAL       54990
Name: MSRP, dtype: int64

In [54]:
# Getting back the numpy array from a Series

df.MSRP.values

array([ 2000, 27150, 54990, 34450, 32340])

In [ ]:
df.groupby('Transmission Type').MSRP.max().values